s="TTCTACTTCTTGACCAAGCTATTAGTATTCTGAACTGCGCTCATGGCATCAGGTTCCGCATAAAAGTGTGCATGCGGGGAGGCGAGAGAGGTTGGGGCAGCCGAGAGAAAACATGGCCGGATCTGCACAAACCACAGCCCATCAAGAAGTTATTAGCCGGGCGCTGTCTGTCCCTAGCAGATAGAAATACATCACCGGTAGCGACAGGCTCCTACTTCTCGAAATCGCACTGGGTGGTCCGACTTCAAGGCCGTACTCCATTATAGAATAACGGGGTCACGGTGCTCTTGCAATGATCGTTCACCTACTTTCCTTGCGTGTAATCACTAGCAACGCGAGACTTCGGTTACTTCATGATACTTGTCAATAGCAATAACTGAGACAAACCGAGACCGGGAATCCTCATGCAACCGCGTATCACATTCCCTCCGCATATACCAGGGATCCATGTAGTAGAGCCCAGACAGGTATGCTGTTTACAAGCATTTTAAATTTGCCTCAAATGTATGGTACCGAGACATCCGAGCTCCGTCTTACCGGTAATCGGTCGATTGCAGTTGCAAAGAGGTAATAAGTAAAACCTGGATGCGAGCCAAGTGCGTTTAATACATTGCATCGATACTAAATAATTTCGTTTACCTGGAATCTGGCATCCGTAAGGTTTTCACCTTAGTTCGGTTCATACGCTCTGTTATCCCTCGCGATTACCGCGTGACGGTCACATCCCTGTCTCCACGCTGAGTTATGCTAGGTCTCACACATTTTCGCGTTGGTACGCACGCTAGCTTGCCAGATCACCTATTGTACCTAGCCATTCGTAAGATTCAGCCTGGAGTTCACGCCGGCACTGGGCGTCAAGACCACTGATTCTGTCGCGCAACGTATATATCACTGTCTAAAAGGATTAAATTAAAGTATTCCAGGAT"
s=s.upper()

t=""

for base in s:
    if base == 'A':
        t+='T'
    elif base == 'C':
        t+='G'
    elif base == 'G':
        t+='C'
    elif base == 'T':
        t+='A'
print t[::-1]
